#!/bin/bash

set -o nounset
set -o errexit
set -o errtrace

ktest_dir=$(dirname "$(readlink -f "$0")")
KTEST=$ktest_dir/ktest

. "$ktest_dir/lib/libktest.sh"

checkdep gcc
checkdep make

KERNEL_SOURCE="."	# dir of kernel source
			#       set with: -k <path>
			#       defaults: current directory
ktest_kernel=""		# dir where the kernel will get built
			#       set with: -b <path>
			#       default: $KERNEL_SOURCE/$DEFAULT_DIR
WORK_DIR=""		# dir where vm meta data (id, logs, etc) gets stored
			#       set with: -w <path>
			#       defaults: $ktest_kernel
BUILD=1			# if set to 1, kernel will build
			#       ignored with: -K (sets to 0)
DEPS=1
COVERAGE=""		# doing code coverage?
MAKEARGS=()
ktest_njobs=$(($(grep -c '^processor' /proc/cpuinfo) * 2))
			# number of jobs to passed to make during kernel compile
			#       sets with: -j
			#       defaults to 2 * number of processor


usage()
{
    echo "build-test-kernel: Run generic virtual machine tests"
    echo "Usage: build-test-kernel cmd [options]"
    ktest_usage_cmds
    echo "  oldconfig   Run make oldconfig"
    echo "  config      Run make nconfig"
    echo
    echo "  options:"
    echo "      -k <dir>    kernel source dir"
    echo "      -b <dir>    build directory for kernel (default: kernel_source/.build-test-kernel)"
    echo "      -w <dir>    work directory (default: kernel build directory)"
    echo "      -c <dir>    enable coverage for this dir (only valid without -K)"
    ktest_usage_opts
    echo
    echo " options for build-test-kernel run:"
    ktest_usage_run_opts
    echo "      -j <num>    j option to make"
    echo "      -K          don't rebuild kernel"
    echo
    ktest_usage_post
}

if [[ $# = 0 ]]; then
    usage
    exit 1
fi

#parse command and shift for rest of arg parsing
CMD="$1"
shift

while getopts "hKDc:b:j:O:${ktest_args}" arg; do
    case $arg in
	h)
	    usage
	    exit 0
	    ;;
	b)
	    KERNEL_SOURCE=$(readlink -e "$OPTARG")
	    ;;
	K)
	    BUILD=""
	    ;;
	D)
	    DEPS=""
	    ;;
	c)
	    if [[ ! -d $OPTARG ]]; then
		echo "$OPTARG must be a directory"
		exit 1
	    fi

	    checkdep lcov

	    # Strip trailing / from directory name, substitute _ for /
	    OPTARG=$(echo "${OPTARG%/}"|tr / _)
	    MAKEARGS+=("GCOV_PROFILE_$OPTARG=y")
	    COVERAGE=1
	    ;;
	j)
	    ktest_njobs=$OPTARG
	    ;;
	O)
	    WORK_DIR=$OPTARG
	    ;;
    esac
    parse_ktest_arg $arg
done
shift $(( OPTIND - 1 ))

# default parameters
[[ -z $WORK_DIR ]]	&& WORK_DIR=$KERNEL_SOURCE/.build_test_kernel-$ARCH
[[ -z $ktest_kernel ]]	&& ktest_kernel=$WORK_DIR/kpkg

mkdir -p "$WORK_DIR"

WORK_DIR=$(readlink -f "$WORK_DIR")
KERNEL_CONFIG="$WORK_DIR/.config"

parse_args_post

if [[ -n $CROSS_COMPILE ]]; then
    checkdep "$ARCH_TRIPLE-gcc" "gcc-$ARCH_TRIPLE"
fi

run_ktest()
{
    arg=$1
    shift

    "$KTEST" "$arg" $KTESTARGS -k "$ktest_kernel" "$@"
}

__do_make()
{
    if [[ -n $CROSS_COMPILE ]]; then
	export ARCH="$KERNEL_ARCH"
	export CROSS_COMPILE="$ARCH_TRIPLE-"
    fi

    if [[ $# = 0 || $1 != nconfig ]]; then
	MAKEARGS+=("--output-sync=target")
    fi

    make --jobs="$ktest_njobs"			\
	--directory="$KERNEL_SOURCE"	    	\
	O="$WORK_DIR"				\
	INSTALL_MOD_PATH="$ktest_kernel"	\
	EXTRA_CFLAGS="-g3"			\
	"${MAKEARGS[@]}"			\
	"$@"
}

new_config()
{
    local kconfig="$WORK_DIR/.config"
    local config_tool="$KERNEL_SOURCE/scripts/config"

    __do_make allnoconfig

    # Really undefine everything:
    sed -i -e 's/\(CONFIG_.*\)=.*/# \1 is not set/' "$kconfig"
}

do_make()
{
    if [[ ! -f $WORK_DIR/.config ]]; then
	new_config
    fi

    __do_make "$@"
}

kernel_opt()
{
    local cmd=$1
    local opt=$2
    local kconfig="$WORK_DIR/.config"
    local config_tool="$KERNEL_SOURCE/scripts/config"

    if [[ $opt =~ = ]]; then
	local val=${opt: -1}
	opt="${opt%=?}"
    else
	local val=y
    fi

    case $cmd in
	set)
	    "$config_tool" --file "$kconfig" --set-val "$opt" "$val"
	    ;;
	check)
	    local c=$("$config_tool" --file "$kconfig" -s "$opt")

	    if [[ $c != $val ]]; then
		echo "Kernel config option $opt is $c; should be $val"
		exit 1
	    fi
	    ;;
    esac
}

build_kernel()
{
    rm -rf "$ktest_kernel"
    mkdir -p "$ktest_kernel"

    if [[ -n $DEPS ]]; then
	local kconfig="$WORK_DIR/.config"
	local config_tool="$KERNEL_SOURCE/scripts/config"

	[[ ! -f $kconfig ]] && new_config

	for opt in "${ktest_kernel_config_require[@]}"; do
	    [[ -n $opt ]] && kernel_opt set "$opt"
	done

	if [[ $BITS = 64 ]]; then
	    kernel_opt set 64BIT
	else
	    kernel_opt clear 64BIT
	fi

	#do_make olddefconfig
	do_make oldnoconfig

	for opt in "${ktest_kernel_config_require[@]}"; do
	    [[ -n $opt ]] && kernel_opt check "$opt"
	done
    fi

    do_make

    local BOOT=$WORK_DIR/arch/$KERNEL_ARCH/boot

    if   [[ -f "$BOOT/bzImage" ]]; then
	install -m0644 "$BOOT/bzImage"		"$ktest_kernel/vmlinuz"
    elif [[ -f "$BOOT/vmlinux.strip" ]]; then
	install -m0644 "$BOOT/vmlinux.strip"	"$ktest_kernel/vmlinuz"
    else
	install -m0644 "$WORK_DIR/vmlinux"	"$ktest_kernel/vmlinuz"
    fi

    install -m0644 "$WORK_DIR/vmlinux" "$ktest_kernel/vmlinux"
    install -m0644 "$WORK_DIR/.config" "$ktest_kernel/config"

    do_make modules_install

    # Remove symlinks, they'll break genisoimage which is following symlinks
    rm -f "$ktest_kernel"/modules/lib/modules/*/build
    rm -f "$ktest_kernel"/modules/lib/modules/*/source
}

cmd_run()
{
    if [[ $# = 0 ]]; then
	echo "build-test-kernel: missing test"
	usage
	exit 1
    fi

    local TEST=$1

    parse_test_deps "$TEST"

    if [[ -n $COVERAGE ]]; then
	ktest_kernel_config_require+=(GCOV_KERNEL)
	ktest_kernel_config_require+=(GCOV_FORMAT_AUTODETECT)
    fi

    if [[ -n $BUILD ]]; then
	run_quiet "building kernel" build_kernel
    fi

    ktest_run "$@"
}

cmd_boot()
{
    cmd_run "$ktest_dir/boot.ktest"
}

cmd_oldconfig()
{
    do_make oldconfig
}

cmd_config()
{
    do_make nconfig
}

cmd_help()
{
    usage
}

if [[ $(type -t "cmd_$CMD") == function ]]; then
    CMD="cmd_$CMD"
elif [[ $(type -t "ktest_$CMD") == function ]]; then
    CMD="ktest_$CMD"
else
    usage
    exit 1
fi

$CMD "$@"
