#!/bin/bash

set -o nounset
set -o errexit
set -o errtrace

KTESTDIR=$(dirname "$(readlink -f "$0")")
KTEST=$KTESTDIR/ktest

. "$KTESTDIR/lib/util.sh"
. "$KTESTDIR/lib/libktest.sh"

checkdep gcc
checkdep make

KERNEL_SOURCE="."	# dir of kernel source
			#       set with: -k <path>
			#       defaults: current directory
KERNEL=""		# dir where the kernel will get built
			#       set with: -b <path>
			#       default: $KERNEL_SOURCE/$DEFAULT_DIR
WORK_DIR=""		# dir where vm meta data (id, logs, etc) gets stored
			#       set with: -w <path>
			#       defaults: $KERNEL
BUILD=1			# if set to 1, kernel will build
			#       ignored with: -K (sets to 0)
DEPS=1
COVERAGE=""		# list of directories to enable code coverage for
NJOBS=$(($(grep -c '^processor' /proc/cpuinfo) * 2))
			# number of jobs to passed to make during kernel compile
			#       sets with: -j
			#       defaults to 2 * number of processor

# config files:
[[ -f $KTESTDIR/ktestrc ]]	&& . "$KTESTDIR/ktestrc"
[[ -f /etc/ktestrc ]]		&& . /etc/ktestrc
[[ -f $HOME/.ktestrc ]]		&& . "$HOME/.ktestrc"

usage()
{
    echo "build-test-kernel: Run generic virtual machine tests"
    echo "Usage: build-test-kernel cmd [options]"
    ktest_usage_cmds
    echo "  oldconfig   Run make oldconfig"
    echo "  config      Run make nconfig"
    echo
    echo "  options:"
    echo "      -x       bash debug statements"
    echo "      -k <dir> kernel source dir"
    echo "      -b <dir> build directory for kernel (default: kernel_source/.build-test-kernel)"
    echo "      -w <dir> work directory (default: kernel build directory)"
    echo "      -c <dir> enable coverage for this dir (only valid without -K)"
    echo
    echo " options for build-test-kernel run:"
    echo "      -K       don't build kernel"
    echo "      -j <num> j option to make"
    echo "      -i <dir> VM root filesystem image"
    echo "      -p <num> hint for test duration (higher is longer, default is 0)"
    echo "      -I       don't automatically stop VM"
    echo "      -S       exit only on test success"
    echo
    ktest_usage_post
}

if [[ $# = 0 ]]; then
    usage
    exit 1
fi

#parse command and shift for rest of arg parsing
CMD="$1"
shift

while getopts "hKDc:b:j:O:${ktest_args}" arg; do
    case $arg in
	h)
	    usage
	    exit 0
	    ;;
	b)
	    KERNEL_SOURCE=$(readlink -e "$OPTARG")
	    ;;
	K)
	    BUILD=""
	    ;;
	D)
	    DEPS=""
	    ;;
	c)
	    if [[ ! -d $OPTARG ]]; then
		echo "$OPTARG must be a directory"
		exit 1
	    fi

	    checkdep lcov

	    # Strip trailing / from directory name, substitute _ for /
	    OPTARG=$(echo "${OPTARG%/}"|tr / _)
	    COVERAGE+=" GCOV_PROFILE_$OPTARG=y"
	    ;;
	j)
	    NJOBS=$OPTARG
	    ;;
	O)
	    WORK_DIR=$OPTARG
	    ;;
    esac
    parse_ktest_arg $arg
done
shift $(( OPTIND - 1 ))

# default parameters
[[ -z $WORK_DIR ]]	&& WORK_DIR=$KERNEL_SOURCE/.build_test_kernel-$ARCH
[[ -z $KERNEL ]]	&& KERNEL=$WORK_DIR/kpkg

mkdir -p "$WORK_DIR"

WORK_DIR=$(readlink -f "$WORK_DIR")
KERNEL_CONFIG="$WORK_DIR/.config"

parse_args_post

checkdep "$ARCH_TRIPLE-gcc" "gcc-$ARCH_TRIPLE"

run_ktest()
{
    arg=$1
    shift

    "$KTEST" "$arg" $KTESTARGS -k "$KERNEL" "$@"
}

__do_make()
{
    export ARCH="$KERNEL_ARCH"
    export CROSS_COMPILE="$ARCH_TRIPLE-"

    local MAKE=(make)
    MAKE+=(--jobs="$NJOBS")
    MAKE+=(--directory="$KERNEL_SOURCE")
    MAKE+=(O="$WORK_DIR")
    MAKE+=(INSTALL_MOD_PATH="$KERNEL")
    MAKE+=(EXTRA_CFLAGS="-g3")
    MAKE+=($COVERAGE)
    MAKE+=("$@")

    if [[ $# = 0 || $1 != nconfig ]]; then
	MAKE+=("--output-sync=target")
    fi

    local quiet=1
    if [[ $# = 1 && $1 = nconfig ]]; then
	quiet=0
    fi

    if [[ $VERBOSE = 1 ]]; then
	quiet=0
    fi

    if [[ $quiet = 1 ]]; then
	get_tmpdir
	local out="$TMPDIR/build_output"

	if ! "${MAKE[@]}" > $out 2>&1; then
	    echo
	    cat "$out"
	    exit 1
	fi
    else
	"${MAKE[@]}"
    fi
}

new_config()
{
    local kconfig="$WORK_DIR/.config"
    local config_tool="$KERNEL_SOURCE/scripts/config"

    __do_make allnoconfig

    # Really undefine everything:
    sed -i -e 's/\(CONFIG_.*\)=.*/# \1 is not set/' "$kconfig"
}

do_make()
{
    if [[ ! -f $WORK_DIR/.config ]]; then
	new_config
    fi

    __do_make "$@"
}

kernel_opt()
{
    local cmd=$1
    local opt=$2
    local kconfig="$WORK_DIR/.config"
    local config_tool="$KERNEL_SOURCE/scripts/config"

    if [[ $opt =~ = ]]; then
	local val=${opt: -1}
	opt="${opt%=?}"
    else
	local val=y
    fi

    case $cmd in
	set)
	    "$config_tool" --file "$kconfig" --set-val "$opt" "$val"
	    ;;
	check)
	    local c=$("$config_tool" --file "$kconfig" -s "$opt")

	    if [[ $c != $val ]]; then
		echo "Kernel config option $opt is $c; should be $val"
		exit 1
	    fi
	    ;;
    esac
}

build_kernel()
{
    rm -rf "$KERNEL"
    mkdir -p "$KERNEL"

    echo -n "building kernel... "

    if [[ -n $DEPS ]]; then
	local kconfig="$WORK_DIR/.config"
	local config_tool="$KERNEL_SOURCE/scripts/config"

	[[ ! -f $kconfig ]] && new_config

	local OLDIFS=$IFS
	IFS=','

	for opt in $_KERNEL_CONFIG_REQUIRE; do
	    [[ -n $opt ]] && kernel_opt set "$opt"
	done

	if [[ $BITS = 64 ]]; then
	    kernel_opt set 64BIT
	else
	    kernel_opt clear 64BIT
	fi

	#do_make olddefconfig
	do_make oldnoconfig

	for opt in $_KERNEL_CONFIG_REQUIRE; do
	    [[ -n $opt ]] && kernel_opt check "$opt"
	done

	IFS=$OLDIFS
    fi

    do_make

    local BOOT=$WORK_DIR/arch/$KERNEL_ARCH/boot

    if   [[ -f "$BOOT/bzImage" ]]; then
	install -m0644 "$BOOT/bzImage"		"$KERNEL/vmlinuz"
    elif [[ -f "$BOOT/vmlinux.strip" ]]; then
	install -m0644 "$BOOT/vmlinux.strip"	"$KERNEL/vmlinuz"
    else
	install -m0644 "$WORK_DIR/vmlinux"	"$KERNEL/vmlinuz"
    fi

    install -m0644 "$WORK_DIR/vmlinux" "$KERNEL/vmlinux"
    install -m0644 "$WORK_DIR/.config" "$KERNEL/config"

    do_make modules_install
    echo done

    # Remove symlinks, they'll break genisoimage which is following symlinks
    rm -f "$KERNEL"/modules/lib/modules/*/build
    rm -f "$KERNEL"/modules/lib/modules/*/source
}

cmd_run()
{
    if [[ $# = 0 ]]; then
	echo "build-test-kernel: missing test"
	usage
	exit 1
    fi

    local TEST=$1

    parse_test_deps "$TEST"

    if [[ -n $COVERAGE ]]; then
	_KERNEL_CONFIG_REQUIRE+=",GCOV_KERNEL"
	_KERNEL_CONFIG_REQUIRE+=",GCOV_FORMAT_AUTODETECT"
    fi

    [[ -n $BUILD ]] && build_kernel

    ktest_run "$@"
}

cmd_boot()
{
    cmd_run "$KTESTDIR/boot.ktest"
}

cmd_oldconfig()
{
    do_make oldconfig
}

cmd_config()
{
    do_make nconfig
}

cmd_help()
{
    usage
}

if [[ $(type -t "cmd_$CMD") == function ]]; then
    CMD="cmd_$CMD"
elif [[ $(type -t "ktest_$CMD") == function ]]; then
    CMD="ktest_$CMD"
else
    usage
    exit 1
fi

$CMD "$@"
