#!/bin/bash

set -o nounset
set -o errexit

if [ "$#" -eq 0 ]; then
    echo "Usage: coveragetool <outputdir> <inputs>..."
    exit 1
fi

if ! which lcov > /dev/null; then
    echo "lcov not installed"
    exit 0
fi

lcov_out="$1"
shift

info=$lcov_out/lcov.info
html=$lcov_out/lcov.html
tracefiles=""

mkdir -p "$lcov_out"

n=0

for dir in $@; do
    out=$lcov_out/lcov.${n}.info
    tracefiles+=" --add-tracefile $out"

    lcov --capture --quiet --directory "$dir" --output-file "$out"

    n=$((n+1))
done

[ -n "$tracefiles" ] || return 0

lcov --quiet --output-file "$info" $tracefiles
genhtml --output-directory "$html" "$info"

echo
echo "LCOV report: file://$html/index.html"
