#!/bin/bash -e
#
# Create a VM image suitable for running automated tests
# Output: vm_image

KTESTDIR=$(dirname $(readlink -f $0))

. $KTESTDIR/util.sh

usage()
{
	echo "create_vm_image: Create a virtual machine image for ktest"
	echo "Usage: create_vm_image filename"
}

OUT=$1
if [ -z "$OUT" ]; then
	usage
	exit
fi

if [ `id -u` != 0 ] ; then
	echo this script must be run as root
	exit 1
fi

checkdep fallocate util-linux
checkdep mkfs.ext4 e2fsprogs
checkdep debootstrap

MNT="$OUT".mnt
SIZE=$((2 * 1024 * 1024 * 1024)) # 2GB

PACKAGES="less,psmisc,openssh-server"
PACKAGES+=",make,gcc,g++,gdb,strace"
PACKAGES+=",xfsprogs,mdadm,lvm2,aoetools,vblade"
PACKAGES+=",linux-tools,blktrace,sysstat,fio,dbench,bonnie++"

EXCLUDE="dmidecode,nano,rsyslog,logrotate,cron,iptables,nfacct"
EXCLUDE+=",debconf-i18n,info"

fallocate -l $SIZE $OUT
mkfs.ext4 -F $OUT
mkdir -p $MNT
mount -o loop $OUT $MNT

debootstrap --include="$PACKAGES" --exclude="$EXCLUDE" sid "$MNT" http://debian-cache:3142/debian/

cat > "$MNT/etc/fstab" <<-ZZ
debugfs				/sys/kernel/debug	debugfs		defaults	0	0
configfgs			/sys/kernel/config	configfs	defaults	0	0
ZZ

cat > "$MNT/etc/network/interfaces" <<-ZZ
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
ZZ

cat > "$MNT/etc/rc.local" <<-ZZ
#!/bin/bash

mount /dev/sr0 /cdrom
PATH=/cdrom:$PATH
cd /cdrom
exec ./rc
ZZ
chmod 755 "$MNT/etc/rc.local"

mkdir -p "$MNT/cdrom"

mkdir -p "$MNT/root/.ssh"
install -m0600 $KTESTDIR/id_dsa.pub "$MNT/root/.ssh/authorized_keys"

umount $MNT
rmdir $MNT
