#!/bin/bash

require-lib ../test-libs.sh
require-bin make-bcache
require-kernel-config MD,BCACHE

config-scratch-devs 2G
config-mem 256M

main()
{
    SIZE=small
    FS=bcachefs
    FLAGS="--bucket 64k --block 2k --discard --writeback --cache_replacement_policy=lru"
    CACHE="/dev/vda"
    BDEV=
    TIER=

    setup_tracing 64 'bcache:*'

    setup_bcache

    test_sysfs

    test_shrink &
    test_fault &
    test_sync &
    test_drop_caches &

    setup_fs

    #test_stress
    test_fsx

    test_success
}
