#!/bin/bash

if [ "$1" = "deps" ]; then
    cat <<-ZZ
REQUIRE=../test-libs.sh,make-bcache,cache_test/cache_torture_test
KERNEL_CONFIG_REQUIRE=BCACHE
MEM=256M
SCRATCH=265M
ZZ
    exit
fi

. test-libs.sh

CACHE=/dev/vda
DEV=bcache0

make-bcache --bucket 128k --block 4k			\
	--discard					\
	--cache_replacement_policy=lru			\
	--cache $CACHE

for dev in $CACHE; do
    echo $dev > /sys/fs/bcache/register
done

rm -f /root/c
ln -s /sys/fs/bcache/*-* /root/c

test_sysfs

cache_set_settings

for dev in $DEV; do
    if [ ! -b $dev ]; then
        echo 256M > /sys/fs/bcache/*/flash_vol_create
    fi
done

udevadm settle
wait_on_dev bcache0

cache_torture_test /dev/bcache0

echo o > /proc/sysrq-trigger
