#!/bin/bash

require-lib ../test-libs.sh
require-bin make-bcache
require-kernel-config MD,BCACHE

config-scratch-devs 256M,1G
config-mem 256M

main()
{
    SIZE=small
    FS=ext4
    FLAGS="--bucket 64k --block 4k --discard --writeback --cache_replacement_policy=lru"
    CACHE="/dev/vda"
    BDEV="/dev/vdb"
    TIER=

    setup_tracing 64 'bcache:*'

    setup_bcache
    test_stress &

    sleep 20

    killall fio bonnie++ dbench || true
    sleep 1

    test_stop

    test_success
}
