#!/bin/bash

require-lib ../test-libs.sh
require-bin make-bcache
require-kernel-config MD,BCACHE

config-scratch-devs 4G
config-mem 256M

main()
{
    SIZE=small
    FS=ext4
    FLAGS="--bucket 512k --block 2k --discard --cache_replacement_policy=lru"
    CACHE="/dev/vda"
    BDEV=
    TIER=

    setup_tracing 64 'bcache:*'

    setup_bcache
    setup_flash_volume 1400M
    test_stress
    stop_bcache

    test_success
}
