#!/bin/bash

require-lib ../test-libs.sh
require-bin make-bcache
require-kernel-config MD,BCACHE

config-scratch-devs 2G,4G
config-mem 256M

config-timeout 600

main()
{
    SIZE=small
    FS=ext4
    FLAGS="--bucket 64k --block 4k --discard --writeback --cache_replacement_policy=lru"
    CACHE="/dev/vda"
    BDEV=
    TIER="/dev/vdb"

    setup_tracing 64 'bcache:*'

    setup_bcache
    setup_flash_volume 1600M
    test_stress
    stop_bcache

    test_success
}
