#!/bin/bash

if [ "$1" = "deps" ]; then
	echo "REQUIRE=test-libs.sh,make-bcache"
	echo "MEM=256M"
	echo "SCRATCH=2G"
	exit
fi

echo "file inode.c +p"		> /sys/kernel/debug/dynamic_debug/control
#echo "file dirent.c +p"		> /sys/kernel/debug/dynamic_debug/control
echo "file fs.c +p"		> /sys/kernel/debug/dynamic_debug/control

. test-libs.sh

CACHE=/dev/vda

echo $CACHE > /sys/fs/bcache/register

if [ $? -ne 0 ]; then
	make-bcache --bucket 64k --block 2k			\
		--discard					\
		--cache_replacement_policy=lru			\
		--cache $CACHE

	echo $CACHE	> /sys/fs/bcache/register
fi
sleep 0.5

#prep_bcache_devices || exit
#cache_set_settings

echo "register done"

cd /sys/fs/bcache
UUID=`ls -d *-*-*`

echo
echo "cache set uuid $UUID"
echo "Mounting bcachefs"

cd

DEV=bcache
mkdir -p /mnt/$DEV

mount -t bcachefs $UUID /mnt/$DEV

test_stress &
