#!/bin/bash

if [ "$1" = "deps" ]; then
    cat <<-ZZ
REQUIRE=../test-libs.sh,make-bcache,../ltp-fsx
KERNEL_CONFIG_REQUIRE=MD,BCACHE
MEM=256M
SCRATCH=2G
ZZ
    exit
fi

. test-libs.sh

echo "file inode.c +p"		> /sys/kernel/debug/dynamic_debug/control
#echo "file dirent.c +p"		> /sys/kernel/debug/dynamic_debug/control
echo "file fs.c +p"		> /sys/kernel/debug/dynamic_debug/control

CACHE=/dev/vda

echo $CACHE > /sys/fs/bcache/register

if [ $? -ne 0 ]; then
	make-bcache --bucket 64k --block 2k			\
		--discard					\
		--cache_replacement_policy=lru			\
		--cache $CACHE

	echo $CACHE	> /sys/fs/bcache/register
fi
sleep 0.5

#prep_bcache_devices || exit
#cache_set_settings

cd /sys/fs/bcache
UUID=`ls -d *-*-*`

echo "register done, mounting $UUID"

DEV=bcache
mkdir -p /mnt/$DEV

cd /
mount -t bcachefs $UUID /mnt/$DEV

test_shrink &
ltp-fsx /mnt/$DEV/foo

#test_stress &
