#!/bin/bash

require-lib ../test-libs.sh
require-bin make-bcache
require-kernel-config MD,BCACHE

config-scratch-devs 256M,256M,256M,2G
config-mem 256M

main()
{
    SIZE=small
    FS=ext4
    FLAGS="--bucket 64k --block 4k --discard --writeback --cache_replacement_policy=lru"
    CACHE="/dev/vda /dev/vdb /dev/vdc /dev/vdd"
    BDEV="/dev/vde"
    TIER=

    setup_tracing 64 'bcache:*'

    setup_bcache

    echo 4 > /sys/fs/bcache/*/meta_replicas
    echo 4 > /sys/fs/bcache/*/data_replicas

    test_stress
    stop_bcache

    test_success
}
