#!/bin/bash

if [ "$1" = "deps" ]; then
	echo "REQUIRE=test-libs.sh,make-bcache"
	echo "MEM=256M"
	echo "SCRATCH=512M,2G,2G"
	exit
fi

. test-libs.sh

CACHE=vda
BDEV="vdb vdc"
DEV="bcache0 bcache1"

prep_bcache_devices || exit

test_sysfs

cache_set_settings
cached_dev_settings

test_shrink &
test_fault &

test_fio $DEV

#prep_mounts || exit
#test_stress &

#test_bcache_test &

#test_stop &
#test_powerfail
