#!/bin/bash

set -e

if [ "$1" = "deps" ]; then
    cat <<-ZZ
REQUIRE=test-libs.sh
KERNEL_CONFIG_REQUIRE=EXT4_FS
MEM=256M
SCRATCH=2G
ZZ
    exit
fi

. test-libs.sh

SIZE=small
FS=ext4

#echo "file inode.c +p"		> /sys/kernel/debug/dynamic_debug/control
#echo "file dirent.c +p"	> /sys/kernel/debug/dynamic_debug/control
#echo "file fs.c +p"		> /sys/kernel/debug/dynamic_debug/control

setup_blkdev
test_stress

test_success
