#!/bin/bash

if [ "$1" = "deps" ]; then
    cat <<-ZZ
REQUIRE=test-libs.sh
KERNEL_CONFIG_REQUIRE=EXT4_FS
MEM=256M
SCRATCH=2G
ZZ
    exit
fi

#echo "file inode.c +p"		> /sys/kernel/debug/dynamic_debug/control
#echo "file dirent.c +p"		> /sys/kernel/debug/dynamic_debug/control
#echo "file fs.c +p"		> /sys/kernel/debug/dynamic_debug/control

. test-libs.sh

mkfs.ext4 /dev/vda
DEV=bcache
mkdir -p /mnt/$DEV

mount /dev/vda /mnt/$DEV

test_stress &
