#!/usr/bin/env bash

TESTDIR=$(dirname "$(readlink -f "$0")")
KTEST="$TESTDIR/../ktest"

do_test()
{
    local t=$1
    local expect=$2

    $KTEST run "$TESTDIR/$t"
    local ret=$?

    if [[ $ret != $expect ]]; then
	echo "$t failed: got $ret, wanted $expect"
	exit 1
    fi
}

do_test success.ktest	0
do_test failure.ktest	1
do_test crash.ktest	1
do_test timeout.ktest	1
