#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

# Warning: this test has currently several timers and requires that
# - the vm gets up and fully initialized in less than 30 seconds
# - the kill process ends and is no longer killable 5 seconds after
#   sendinf the kill signal
# In a highly loaded system this could be a problem, in which case 
# either the timers have to be increased, or the timers need to be 
# replaced with code that checks if everything is ready.

KERNEL=/usr/share/DateraContainer/kernel
KTESTDIR=/src/ktest
KTEST=$KTESTDIR/ktest

opt="-w workdir.$$ -K -b $KERNEL -k $KERNEL"

( 
   sleep 10
   echo 'killall sleep' | $KTEST ssh $opt
) &
pid="$!"

$KTEST run $opt $KTESTDIR/tests/ktest.ktest
ret="$?"

sleep 5 
# give the the kill process some time to exit

if kill $pid > /dev/null 2>&1; then
   ret=1
   # if the test passed the kill process should not exist anymore
fi

stty sane

exit $ret

