#!/bin/bash -e
#
# Create a VM image suitable for running automated tests
# Output: vm_image

VM_IMAGE_DIR=$(dirname $(readlink -f $0))
KTESTDIR=$VM_IMAGE_DIR/..

. $KTESTDIR/util.sh

. $VM_IMAGE_DIR/create_vm_image_common.sh

checkdep yum rpm

# This bootstrap can only run with the versions
# of yum+rpm on RHEL 7 or a later Fedora, not on debian.
source /etc/os-release
test "$ID" = "dateros"
test "$VERSION_ID" = "0.5.1"


COREPKGS="basesystem bash biosdevname btrfs-progs coreutils"
COREPKGS+=" curl dhclient e2fsprogs filesystem glibc hostname"
COREPKGS+=" initscripts iproute iptables iputils kbd less man-db"
COREPKGS+=" ncurses openssh-clients openssh-server parted passwd"
COREPKGS+=" policycoreutils procps-ng rpm setup shadow-utils"
COREPKGS+=" sudo systemd tar util-linux vim-minimal xfsprogs yum"
COREPKGS+=" NetworkManager"

PACKAGES="less psmisc openssh-server"
PACKAGES+=" make gcc gcc-g++ gdb strace"
PACKAGES+=" hdparm xfsprogs btrfs-progs mdadm lvm2 aoetools vblade"
PACKAGES+=" linux-tools blktrace sysstat fio dbench bonnie++"
PACKAGES+=" libunwind  libdwarf libdwarf-devel"
PACKAGES+=" elfutils-libelf elfutils-libelf-devel elfutils-libs elfutils-devel"
PACKAGES+=" numactl-devel numactl-libs perl perl-libs perl-devel"
PACKAGES+=" libunwind libunwind-devel"
PACKAGES+=" libuuid libuuid-devel uuid-perl"
PACKAGES+=" net-tools htop python-magic perf python-perf"
PACKAGES+=" kexec-tools libnih"

create_mount_image "$@"

mkdir -p "${MNT}/dev/pts" "${MNT}/dev/shm"
ln -s /proc/self/fd/0 "${MNT}/dev/stdin"
ln -s /proc/self/fd/1 "${MNT}/dev/stdout"
ln -s /proc/self/fd/2 "${MNT}/dev/stderr"

mknod -m 666 "${MNT}/dev/null" c 1 3
mknod -m 666 "${MNT}/dev/zero" c 1 5
mknod -m 666 "${MNT}/dev/full" c 1 7
mknod -m 666 "${MNT}/dev/random" c 1 8
mknod -m 666 "${MNT}/dev/urandom" c 1 9
mknod -m 644 "${MNT}/dev/kmsg" c 1 11
mknod -m 666 "${MNT}/dev/tty" c 5 0
mknod -m 600 "${MNT}/dev/console" c 5 1
mknod -m 666 "${MNT}/dev/ptmx" c 5 2

mkdir -p "${MNT}/var/lib/rpm" "${MNT}/etc/yum.repos.d"
rpm --root "$MNT" --initdb

cat > $MNT/.yum.config <<-ZZ
[main]
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=0
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=3
reposdir=${CHROOTPATH}/etc/yum.repos.d
ZZ

cat >> $MNT/etc/yum.repos.d/install.repo <<-ZZ
[centos-7-os]
name=centos-7-os
baseurl=http://mirrors.daterainc.com/mirrors/centos-7/os/x86_64/
gpgcheck=0

[centos-7-extras]
name=centos-7-extras
baseurl=http://mirrors.daterainc.com/mirrors/centos-7/extras/x86_64/
gpgcheck=0

[centos-7-updates]
name=centos-7-updates
baseurl=http://mirrors.daterainc.com/mirrors/centos-7/updates/x86_64/
gpgcheck=0

[epel-7-x86_64]
name=epel-7-x86_64
baseurl=http://mirrors.daterainc.com/mirrors/epel-7-x86_64/
gpgcheck=0

[centos-7-ports]
name=centos-7-ports
baseurl=http://mirrors.daterainc.com/mirrors/centos-7-ports/
gpgcheck=0
ZZ

yum -c "$MNT/.yum.config" \
    --installroot="$MNT" \
    --releasever="7Everything" \
    -y install $COREPKGS $PACKAGES

rm -rf "$MNT/var/cache/yum/*"

cat > "$MNT/etc/systemd/system.conf" <<-ZZ
[Manager]
LogColor=no
LogTarget=console
LogLevel=info
ShowStatus=no
DefaultStandardOutput=journal+console
DefaultStandardError=journal+console
ZZ

cp $VM_IMAGE_DIR/rc.local "$MNT/etc/rc.d/rc.local"
chmod 755 "$MNT/etc/rc.d/rc.local"

chroot "$MNT" systemctl mask				\
    getty.target					\
    kdump.service					\
    avahi-daemon.service				\
    crond.service					\
    lvm2-lvmetad.service				\
    lvm2-monitor.service				\
    rsyslog.service					\
    polkit.service

finish_umount_image
