#!/bin/bash -e
#
# Create a VM image suitable for running automated tests
# Output: vm_image

VM_IMAGE_DIR=$(dirname $(readlink -f $0))
KTESTDIR=$VM_IMAGE_DIR/..

. $KTESTDIR/util.sh

. $VM_IMAGE_DIR/create_vm_image_common.sh

checkdep debootstrap

PACKAGES="kexec-tools,less,psmisc,openssh-server"
PACKAGES+=",make,gcc,g++,gdb,strace,valgrind"
PACKAGES+=",hdparm,xfsprogs,btrfs-tools,mdadm,lvm2,aoetools,vblade"
PACKAGES+=",linux-tools,blktrace,sysstat,fio,dbench,bonnie++"

EXCLUDE="dmidecode,nano,rsyslog,logrotate,cron,iptables,nfacct"
EXCLUDE+=",debconf-i18n,info,gnupg"

MIRROR=http://ftp.us.debian.org/debian/

create_mount_image $1

debootstrap --include="$PACKAGES" --exclude="$EXCLUDE" sid "$MNT" $MIRROR

cat > "$MNT/etc/network/interfaces" <<-ZZ
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
ZZ

cp $VM_IMAGE_DIR/rc.local "$MNT/etc/rc.local"
chmod 755 "$MNT/etc/rc.local"

chroot "$MNT" systemctl mask				\
    dev-hvc0.device					\
    getty.target					\
    getty-static.service				\
    avahi-daemon.service				\
    crond.service					\
    kdump.service					\
    hdparm.service					\
    cdrom.mount						\
    mdadm-raid.service					\
    lvm2-lvmetad.service				\
    lvm2-monitor.service				\
    lvm2-lvmetad.socket					\
    lvm2-activation-early.service			\
    lvm2-activation.service				\
    dm-event.socket					\
    aoetools.service					\
    sysstat.service					\
    kexec-load.service					\
    kexec.service					\
    systemd-ask-password-console.path			\
    systemd-ask-password-wall.path			\
    systemd-update-utmp-runlevel.service		\
    systemd-update-utmp.service				\
    systemd-journald.service				\
    systemd-journal-flush.service			\
    systemd-journald-dev-log.socket			\
    systemd-journald.socket

rm "$MNT/lib/udev/rules.d/*persistent*"
rm "$MNT/lib/udev/rules.d/*lvm*"
rm "$MNT/lib/udev/rules.d/*dm*"
rm "$MNT/lib/udev/rules.d/*md-raid*"
rm "$MNT/lib/udev/rules.d/*btrfs*"
rm "$MNT/lib/udev/rules.d/*hdparm*"

finish_umount_image
