#!/bin/bash

. $(dirname $(readlink -e ${BASH_SOURCE[0]}))/../test-libs.sh

config-timeout		60
config-mem		512M
config-scratch-devs	1G

require-make aio-multithread-test.mak aio-multithread-test

main()
{
    DEV=sdb

    #echo "file aio.c +p" > /sys/kernel/debug/dynamic_debug/control
    #echo "func do_io_submit  +p"	> /sys/kernel/debug/dynamic_debug/control
    #echo "func io_submit_one +p"	> /sys/kernel/debug/dynamic_debug/control
    #echo "func aio_run_iocb  +p"	> /sys/kernel/debug/dynamic_debug/control

    /cdrom/aio-multithread-test /dev/$DEV
}
